version: '3'
services:
  wiki:
    build:
      context: . # Points to the directory with Dockerfile and modules folder
    environment:
      DB_TYPE: sqlite
      DB_FILEPATH: /wiki/data/database.sqlite
    container_name: wiki
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki-http.rule=Host(`wiki.apps.zidartcc.org`)
      - traefik.http.routers.wiki-http.entrypoints=web
      - traefik.http.routers.wiki-https.tls=true
      - traefik.http.routers.wiki-https.tls.certresolver=cloudflare
      - traefik.http.routers.wiki-https.entrypoints=websecure
      - traefik.http.routers.wiki-https.rule=Host(`wiki.apps.zidartcc.org`)
    ports:
      - '3000'
    volumes:
      - db-data:/wiki/data # Persistent storage for SQLite database

volumes:
  db-data:
networks:
  frontend:
    external: true
