name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Files to VPS
        run: |
          scp -r . docker-user@apps.zidartcc.org:/home/docker/wiki

      - name: Deploy with Docker Compose
        run: |
          ssh docker-user@apps.zidartcc.org "cd /home/docker/wiki && docker-compose pull && docker-compose up -d --build"
